// car
export const ADDTOCART = 'ADDTOCART'
export const INPUTCART = 'INPUTCART'
export const REMOVECARTITEM = 'REMOVECARTITEM'
export const EMPTYCART = 'EMPTYCART'
// products
export const GETALLDATA = 'GETALLDATA'
export const DECREMNETPRODUCT = 'DECREMNETPRODUCT'
export const INCREMENTPRODUCT = 'INCREMENTPRODUCT'
export const CHANGEPRODUCT = 'CHANGEPRODUCT'
export const RESTOREPRODUCT = 'RESTOREPRODUCT'
export const EMPTYPRODUCT = 'EMPTYPRODUCT'